# Generated by Django 4.2.1 on 2023-11-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todo_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='tasks',
            new_name='user',
        ),
    ]
